// Generated by gencpp from file guide_navigation/GuideNavigationResponse.msg
// DO NOT EDIT!


#ifndef GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONRESPONSE_H
#define GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace guide_navigation
{
template <class ContainerAllocator>
struct GuideNavigationResponse_
{
  typedef GuideNavigationResponse_<ContainerAllocator> Type;

  GuideNavigationResponse_()
    : result()  {
    }
  GuideNavigationResponse_(const ContainerAllocator& _alloc)
    : result(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _result_type;
  _result_type result;





  typedef boost::shared_ptr< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> const> ConstPtr;

}; // struct GuideNavigationResponse_

typedef ::guide_navigation::GuideNavigationResponse_<std::allocator<void> > GuideNavigationResponse;

typedef boost::shared_ptr< ::guide_navigation::GuideNavigationResponse > GuideNavigationResponsePtr;
typedef boost::shared_ptr< ::guide_navigation::GuideNavigationResponse const> GuideNavigationResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace guide_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'move_base_msgs': ['/opt/ros/kinetic/share/move_base_msgs/cmake/../msg'], 'guide_navigation': ['/home/kobuki/ws_moveit/devel/share/guide_navigation/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c22f2a1ed8654a0b365f1bb3f7ff2c0f";
  }

  static const char* value(const ::guide_navigation::GuideNavigationResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc22f2a1ed8654a0bULL;
  static const uint64_t static_value2 = 0x365f1bb3f7ff2c0fULL;
};

template<class ContainerAllocator>
struct DataType< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "guide_navigation/GuideNavigationResponse";
  }

  static const char* value(const ::guide_navigation::GuideNavigationResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string result\n\
\n\
";
  }

  static const char* value(const ::guide_navigation::GuideNavigationResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.result);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GuideNavigationResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::guide_navigation::GuideNavigationResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::guide_navigation::GuideNavigationResponse_<ContainerAllocator>& v)
  {
    s << indent << "result: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.result);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONRESPONSE_H
