// Generated by gencpp from file guide_navigation/GuideNavigationRequest.msg
// DO NOT EDIT!


#ifndef GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONREQUEST_H
#define GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace guide_navigation
{
template <class ContainerAllocator>
struct GuideNavigationRequest_
{
  typedef GuideNavigationRequest_<ContainerAllocator> Type;

  GuideNavigationRequest_()
    : location(0)  {
    }
  GuideNavigationRequest_(const ContainerAllocator& _alloc)
    : location(0)  {
  (void)_alloc;
    }



   typedef uint32_t _location_type;
  _location_type location;





  typedef boost::shared_ptr< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> const> ConstPtr;

}; // struct GuideNavigationRequest_

typedef ::guide_navigation::GuideNavigationRequest_<std::allocator<void> > GuideNavigationRequest;

typedef boost::shared_ptr< ::guide_navigation::GuideNavigationRequest > GuideNavigationRequestPtr;
typedef boost::shared_ptr< ::guide_navigation::GuideNavigationRequest const> GuideNavigationRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace guide_navigation

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'move_base_msgs': ['/opt/ros/kinetic/share/move_base_msgs/cmake/../msg'], 'guide_navigation': ['/home/kobuki/ws_moveit/devel/share/guide_navigation/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0d617cc4938cb7c089855b6172bb218d";
  }

  static const char* value(const ::guide_navigation::GuideNavigationRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0d617cc4938cb7c0ULL;
  static const uint64_t static_value2 = 0x89855b6172bb218dULL;
};

template<class ContainerAllocator>
struct DataType< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "guide_navigation/GuideNavigationRequest";
  }

  static const char* value(const ::guide_navigation::GuideNavigationRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "uint32 location\n\
";
  }

  static const char* value(const ::guide_navigation::GuideNavigationRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct GuideNavigationRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::guide_navigation::GuideNavigationRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::guide_navigation::GuideNavigationRequest_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    Printer<uint32_t>::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATIONREQUEST_H
