// Generated by gencpp from file guide_navigation/GuideNavigation.msg
// DO NOT EDIT!


#ifndef GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATION_H
#define GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATION_H

#include <ros/service_traits.h>


#include <guide_navigation/GuideNavigationRequest.h>
#include <guide_navigation/GuideNavigationResponse.h>


namespace guide_navigation
{

struct GuideNavigation
{

typedef GuideNavigationRequest Request;
typedef GuideNavigationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GuideNavigation
} // namespace guide_navigation


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::guide_navigation::GuideNavigation > {
  static const char* value()
  {
    return "1c97203abdbe5a7708232294d90cda4f";
  }

  static const char* value(const ::guide_navigation::GuideNavigation&) { return value(); }
};

template<>
struct DataType< ::guide_navigation::GuideNavigation > {
  static const char* value()
  {
    return "guide_navigation/GuideNavigation";
  }

  static const char* value(const ::guide_navigation::GuideNavigation&) { return value(); }
};


// service_traits::MD5Sum< ::guide_navigation::GuideNavigationRequest> should match 
// service_traits::MD5Sum< ::guide_navigation::GuideNavigation > 
template<>
struct MD5Sum< ::guide_navigation::GuideNavigationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::guide_navigation::GuideNavigation >::value();
  }
  static const char* value(const ::guide_navigation::GuideNavigationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::guide_navigation::GuideNavigationRequest> should match 
// service_traits::DataType< ::guide_navigation::GuideNavigation > 
template<>
struct DataType< ::guide_navigation::GuideNavigationRequest>
{
  static const char* value()
  {
    return DataType< ::guide_navigation::GuideNavigation >::value();
  }
  static const char* value(const ::guide_navigation::GuideNavigationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::guide_navigation::GuideNavigationResponse> should match 
// service_traits::MD5Sum< ::guide_navigation::GuideNavigation > 
template<>
struct MD5Sum< ::guide_navigation::GuideNavigationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::guide_navigation::GuideNavigation >::value();
  }
  static const char* value(const ::guide_navigation::GuideNavigationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::guide_navigation::GuideNavigationResponse> should match 
// service_traits::DataType< ::guide_navigation::GuideNavigation > 
template<>
struct DataType< ::guide_navigation::GuideNavigationResponse>
{
  static const char* value()
  {
    return DataType< ::guide_navigation::GuideNavigation >::value();
  }
  static const char* value(const ::guide_navigation::GuideNavigationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // GUIDE_NAVIGATION_MESSAGE_GUIDENAVIGATION_H
